"""
Django settings for nwhacks2 project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '76iq8@)rio&i^_51i6trn=)+!u2#+pl$e*!$qg$_w+vgn9sf-v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djangobower',
    'hack16'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
)

ROOT_URLCONF = 'nwhacks2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nwhacks2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'nwhacks',
        'USER': 'nwhacks',
        'PASSWORD': 'nwhacks',
        'HOST': '',
        'PORT': ''
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT_PATH = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    STATIC_ROOT_PATH
]

# django-bower

BOWER_COMPONENTS_ROOT = STATIC_ROOT_PATH

BOWER_INSTALLED_APPS = (
    "app-router#~2.6.1",
    "PolymerElements/iron-ajax#~1.0.6",
    "PolymerElements/iron-form#~1.0.10",
    "PolymerElements/iron-image#~1.0.2",
    "momentjs#~2.10.6",
    "PolymerElements/paper-button#~1.0.8",
    "PolymerElements/paper-card#~1.0.6",
    "PolymerElements/paper-checkbox#~1.0.12",
    "PolymerElements/paper-dialog#~1.0.2",
    "PolymerElements/paper-dropdown-menu#~1.0.5",
    "PolymerElements/paper-input",
    "PolymerElements/paper-item#~1.0.5",
    "PolymerElements/paper-menu#~1.1.1",
    "PolymerElements/paper-scroll-header-panel#~1.0.8",
    "PolymerElements/paper-toolbar#~1.0.4",
    "Polymer/polymer#^1.1.0",
    "PolymerElements/paper-icon-button#~1.0.5"
)
